### ISSUE TITLE
mnnpy fails to import with latest version of numba

### ISSUE THREAD

**Issue by sinclaircooper** [chriscainx/mnnpy#24]
mnnpy (version 0.1.9.5) fails to import when using the latest version of numba (0.44.0). Rolling back to the previous version of numba (0.43.1) fixes this issue. 

Most of the error messages seem to be realted to type errors.

```
Python 3.6.7+ (heads/3.6:bfb8818, Dec  5 2018, 13:28:38) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mnnpy 
/home/sinclair/.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/mnnpy/utils.py:14: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function "l2_norm" failed type inference due to: Invalid use of Function(<function norm at 0x7f43f913cea0>) with argument(s) of type(s): (axis=Literal[int](1), x=array(float32, 2d, A))
 * parameterized
In definition 0:
    TypeError: norm_impl() got an unexpected keyword argument 'x'
    raised from /home/sinclair/.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/numba/typing/templates.py:475
In definition 1:
    TypeError: norm_impl() got an unexpected keyword argument 'x'
    raised from /home/sinclair/.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/numba/typing/templates.py:475
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: Function(<function norm at 0x7f43f913cea0>)
[2] During: typing of call at /home/sinclair/.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/mnnpy/utils.py (16)


File "../.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/mnnpy/utils.py", line 16:
def l2_norm(in_matrix):
    return np.linalg.norm(x=in_matrix, axis=1)
    ^

  @jit(float32[:](float32[:, :]), nogil=True)
/home/sinclair/.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/numba/compiler.py:725: NumbaWarning: Function "l2_norm" was compiled in object mode without forceobj=True.

File "../.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/mnnpy/utils.py", line 15:
@jit(float32[:](float32[:, :]), nogil=True)
def l2_norm(in_matrix):
^

  self.func_ir.loc))
/home/sinclair/.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/numba/compiler.py:734: NumbaDeprecationWarning: 
Fall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated behaviour.

For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit

File "../.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/mnnpy/utils.py", line 15:
@jit(float32[:](float32[:, :]), nogil=True)
def l2_norm(in_matrix):
^

  warnings.warn(errors.NumbaDeprecationWarning(msg, self.func_ir.loc))
/home/sinclair/.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/mnnpy/utils.py:14: NumbaWarning: Code running in object mode won't allow parallel execution despite nogil=True.
  @jit(float32[:](float32[:, :]), nogil=True)
/home/sinclair/.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/mnnpy/utils.py:29: NumbaPerformanceWarning: np.dot() is faster on contiguous arrays, called on (array(float32, 1d, A), array(float32, 1d, A))
  dist[i, j] = np.dot(m[i], n[j])
/home/sinclair/.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/mnnpy/utils.py:88: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function "find_mutual_nn" failed type inference due to: Untyped global name 'cKDTree': cannot determine Numba type of <class 'type'>

File "../.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/mnnpy/utils.py", line 90:
def find_mutual_nn(data1, data2, k1, k2, n_jobs):
    k_index_1 = cKDTree(data1).query(x=data2, k=k1, n_jobs=n_jobs)[1]
    ^

  @jit((float32[:, :], float32[:, :], int8, int8, int8))
/home/sinclair/.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/mnnpy/utils.py:88: NumbaWarning: 
Compilation is falling back to object mode WITHOUT looplifting enabled because Function "find_mutual_nn" failed type inference due to: Untyped global name 'cKDTree': cannot determine Numba type of <class 'type'>

File "../.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/mnnpy/utils.py", line 90:
def find_mutual_nn(data1, data2, k1, k2, n_jobs):
    k_index_1 = cKDTree(data1).query(x=data2, k=k1, n_jobs=n_jobs)[1]
    ^

  @jit((float32[:, :], float32[:, :], int8, int8, int8))
/home/sinclair/.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/numba/compiler.py:725: NumbaWarning: Function "find_mutual_nn" was compiled in object mode without forceobj=True, but has lifted loops.

File "../.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/mnnpy/utils.py", line 89:
@jit((float32[:, :], float32[:, :], int8, int8, int8))
def find_mutual_nn(data1, data2, k1, k2, n_jobs):
^

  self.func_ir.loc))
/home/sinclair/.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/numba/compiler.py:734: NumbaDeprecationWarning: 
Fall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated behaviour.

For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit

File "../.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/mnnpy/utils.py", line 89:
@jit((float32[:, :], float32[:, :], int8, int8, int8))
def find_mutual_nn(data1, data2, k1, k2, n_jobs):
^

  warnings.warn(errors.NumbaDeprecationWarning(msg, self.func_ir.loc))
/home/sinclair/.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/mnnpy/utils.py:102: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function "compute_correction" failed type inference due to: Invalid use of Function(<function unique at 0x7f43f8cdda60>) with argument(s) of type(s): (array(int32, 1d, A), return_counts=bool)
 * parameterized
In definition 0:
    TypeError: np_unique() got an unexpected keyword argument 'return_counts'
    raised from /home/sinclair/.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/numba/typing/templates.py:475
In definition 1:
    TypeError: np_unique() got an unexpected keyword argument 'return_counts'
    raised from /home/sinclair/.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/numba/typing/templates.py:475
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: Function(<function unique at 0x7f43f8cdda60>)
[2] During: typing of call at /home/sinclair/.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/mnnpy/utils.py (105)


File "../.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/mnnpy/utils.py", line 105:
def compute_correction(data1, data2, mnn1, mnn2, data2_or_raw2, sigma):
    <source elided>
    vect = data1[mnn1] - data2[mnn2]
    mnn_index, mnn_count = np.unique(mnn2, return_counts=True)
    ^

  @jit(float32[:, :](float32[:, :], float32[:, :], int32[:], int32[:], float32[:, :], float32))
/home/sinclair/.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/mnnpy/utils.py:102: NumbaWarning: 
Compilation is falling back to object mode WITHOUT looplifting enabled because Function "compute_correction" failed type inference due to: cannot determine Numba type of <class 'numba.dispatcher.LiftedLoop'>

File "../.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/mnnpy/utils.py", line 107:
def compute_correction(data1, data2, mnn1, mnn2, data2_or_raw2, sigma):
    <source elided>
    vect_reduced = np.zeros((data2.shape[0], vect.shape[1]), dtype=np.float32)
    for index, ve in zip(mnn2, vect):
    ^

  @jit(float32[:, :](float32[:, :], float32[:, :], int32[:], int32[:], float32[:, :], float32))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sinclair/.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/mnnpy/__init__.py", line 1, in <module>
    from .mnn import mnn_correct
  File "/home/sinclair/.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/mnnpy/mnn.py", line 7, in <module>
    from .utils import transform_input_data, find_mutual_nn, compute_correction
  File "/home/sinclair/.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/mnnpy/utils.py", line 102, in <module>
    @jit(float32[:, :](float32[:, :], float32[:, :], int32[:], int32[:], float32[:, :], float32))
  File "/home/sinclair/.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/numba/decorators.py", line 186, in wrapper
    disp.compile(sig)
  File "/home/sinclair/.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/sinclair/.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/numba/dispatcher.py", line 659, in compile
    cres = self._compiler.compile(args, return_type)
  File "/home/sinclair/.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/numba/dispatcher.py", line 83, in compile
    pipeline_class=self.pipeline_class)
  File "/home/sinclair/.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/numba/compiler.py", line 955, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/sinclair/.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/numba/compiler.py", line 377, in compile_extra
    return self._compile_bytecode()
  File "/home/sinclair/.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/numba/compiler.py", line 886, in _compile_bytecode
    return self._compile_core()
  File "/home/sinclair/.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/numba/compiler.py", line 873, in _compile_core
    res = pm.run(self.status)
  File "/home/sinclair/.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/sinclair/.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/numba/compiler.py", line 254, in run
    raise patched_exception
  File "/home/sinclair/.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/numba/compiler.py", line 245, in run
    stage()
  File "/home/sinclair/.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/numba/compiler.py", line 463, in stage_objectmode_frontend
    cres = self.frontend_looplift()
  File "/home/sinclair/.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/numba/compiler.py", line 435, in frontend_looplift
    lifted=tuple(loops), lifted_from=None)
  File "/home/sinclair/.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/numba/compiler.py", line 1017, in compile_ir
    lifted_from=lifted_from)
  File "/home/sinclair/.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/numba/compiler.py", line 385, in compile_ir
    return self._compile_ir()
  File "/home/sinclair/.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/numba/compiler.py", line 893, in _compile_ir
    return self._compile_core()
  File "/home/sinclair/.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/numba/compiler.py", line 873, in _compile_core
    res = pm.run(self.status)
  File "/home/sinclair/.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/sinclair/.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/numba/compiler.py", line 254, in run
    raise patched_exception
  File "/home/sinclair/.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/numba/compiler.py", line 245, in run
    stage()
  File "/home/sinclair/.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/numba/compiler.py", line 711, in stage_objectmode_backend
    self._backend(lowerfn, objectmode=True)
  File "/home/sinclair/.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/numba/compiler.py", line 687, in _backend
    lowered = lowerfn()
  File "/home/sinclair/.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/numba/compiler.py", line 659, in backend_object_mode
    self.flags)
  File "/home/sinclair/.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/numba/compiler.py", line 1148, in py_lowering_stage
    lower.lower()
  File "/home/sinclair/.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/numba/lowering.py", line 202, in lower
    self.library.add_ir_module(self.module)
  File "/home/sinclair/.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/numba/targets/codegen.py", line 185, in add_ir_module
    ll_module = ll.parse_assembly(ir)
  File "/home/sinclair/.local/share/virtualenvs/SingleCell-EElUQT2U/lib/python3.6/site-packages/llvmlite/binding/module.py", line 26, in parse_assembly
    raise RuntimeError("LLVM IR parsing error\n{0}".format(errmsg))
RuntimeError: Failed in object mode pipeline (step: object mode frontend)
Failed in object mode pipeline (step: object mode backend)
LLVM IR parsing error
<string>:2781:50: error: expected type
  %".2422" = call i8* @"PyLong_FromSsize_t"(i64 (slice(None, None, None), None))
```

**Comment by deto** [comment]
Having the same error - slew of error messages like this with numba=44.1

**Comment by vincent6liu** [comment]
Same issue. numba=0.44.1, llvmlite=0.29.0

**Comment by flying-sheep** [comment]
This specific one is very easy to fix: Just call `norm(in_matrix, axis=1)` instead of `norm(x=in_matrix, axis=1)`

**Comment by chris-rands** [comment]
@flying-sheep Still results in `TypeError: norm_impl() got an unexpected keyword argument 'axis'`. Looks like the `axis` arg is removed, as the axis is inferred internally, if I interpret the source correctly?

https://github.com/numba/numba/blob/88e3dad3d43a59c79e6295f72fc344d77f13330c/numba/targets/linalg.py#L2365-L2371

However, omitting the `axis` arg led to other tracebacks, leading to `IndexError: invalid index to scalar variable.`?

**Comment by flying-sheep** [comment]
That looks like a numba bug then.
